# Generated by Django 5.0.4 on 2024-06-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
