# Generated by Django 5.0.6 on 2024-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_blogmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('About the food shop', 'お店について'), ('About the menu', 'メニューについて'), ('Others', 'その他')], max_length=50),
        ),
    ]
