# Generated by Django 5.0.4 on 2024-06-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
