# Generated by Django 5.0.4 on 2024-07-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_blogmodel_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='favorites',
        ),
    ]
